name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read # Erforderlich zum Abrufen des Repository-Inhalts
      packages: write # Erforderlich, um auf die GitHub Container Registry zuzugreifen

    steps:
    # Checkout des Repositorys
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Logge dich in die GitHub Container Registry ein
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build des Docker-Images mit dem Tag basierend auf Commit/Tag
    - name: Build Docker Image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        
        # Bestimme den Tag für das Image
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "branch" ]]; then
          TAG=latestt
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
          TAG=${{ github.ref_name }}
        fi

        echo "Building Docker Image ${IMAGE_NAME}:${TAG}"
        
        # Führe den Build aus
        docker build -t ${IMAGE_NAME}:${TAG} deployment/

    # Push des Images in die GitHub Container Registry
    - name: Push Docker Image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        docker push ${IMAGE_NAME}:${TAG}

    # Optional: Cleanup lokaler Docker-Images
    - name: Remove Docker Images
      run: |
        docker image prune -f
